image: node:lts

before_script:
  - npm install

pages:
  script:
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    refs:
      - branches
    changes:
      - package.json
      - src/**/*
      - assets/**/*
      - .gitlab-ci.yml
