image: node:lts

before_script:
  - npm install

pages:
  script:
    - npm run build
    - cp -rv assets .vitepress/dist
    - mv .vitepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main

